In [ ]:
import time
print(time.ctime())

Thu Feb  6 02:39:35 2025


In [ ]:
x = 1
x

1

In [ ]:
x = x + 1
x

2

In [ ]:
x = x + 3
x

5

In [ ]:
x = 1
y = x + 1
x = 2
y

2

In [ ]:
import numpy as np

In [ ]:
x = np.array([1, 4, 3])
x

array([1, 4, 3])

In [ ]:
x = np.array([9, 2, 7])
x

array([9, 2, 7])

In [ ]:
x = np.array([1, 4, 3][9, 2, 7])
x

<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<ipython-input-9-9a5b96995f05>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  x = np.array([1, 4, 3][9, 2, 7])


TypeError: list indices must be integers or slices, not tuple

In [ ]:
x = np.array([1, 4, 3])
x = np.array([9, 2, 7])
x

array([9, 2, 7])

In [ ]:
x = np.array([[1, 4, 3], [9, 2, 7]])
print(x)

[[1 4 3]
 [9 2 7]]


In [ ]:
x = np.array([1, 4, 3], [9, 2, 7])
x

TypeError: Field elements must be 2- or 3-tuples, got '9'

In [ ]:
def my_adder(a, b, c):
  """
  function to sum the 3 numbers
  Input: 3 numbers a, b, c
  Output: the sum of a, b, and c
  author:
  date:
  """

  # this is the summation
  out = a + b + c

  return out

In [ ]:
my_adder(1,2,3)

6

In [ ]:
def my_thermo_stat(temp, desired_temp):
  if temp < desired_temp - 5:
    status = 'Heat'
  elif temp > desired_temp + 5:
    status = 'AC'
  else:
    status = 'off'
  return status

In [ ]:
status = my_thermo_stat(65,75)
print(status)

Heat


In [ ]:
status = my_thermo_stat(75,65)
print(status)

AC


In [ ]:
status = my_thermo_stat(65, 63)
print(status)

off


In [ ]:
x = 3
if x > 1 and x < 2:
  y = 2
elif x > 2 and x < 4:
  y = 4
else:
  y = 0
print(y)

4


In [ ]:
x = 3
if 1 < x < 2:
  y = 2
elif 2 < x < 4:
  y = 4
else:
  y = 0
print(y)

4


In [1]:
def login():
  password = "Bn123"

  input_username = input("Masukkan username anda : ")

  while True:
    input_password = input("Masukkan password anda : ")

    if input_password == password:
      print(f"Login Berhasil, Selamat Datang {input_username}\n")
      break
    else:
      print("Incorrect Password\n")

def calculate(uas, uts, assignment):
  final_score = (0.5 * uas) + (0.3 * uts) + (0.2 * assignment)

  if 90 <= final_score <= 100:
    grade = "A"
  elif 85 <= final_score < 90:
    grade = "A-"
  elif 80 <= final_score < 85:
    grade = "B+"
  elif 75 <= final_score < 80:
    grade = "B"
  elif 70 <= final_score < 75:
    grade = "B-"
  elif 65 <= final_score < 70:
    grade = "C"
  elif 50 <= final_score < 65:
    grade = "D"
  else:
    grade = "E"

  return final_score, grade

def main():
  login()

  nama_siswa = input("Masukkan nama siswa : ")
  uas = int(input("Masukkan Nilai UAS : "))
  uts = int(input("Masukkan Nilai UTS : "))
  assignment = int(input("Masukkan Nilai Assignment : "))

  final_score, grade = calculate(uas, uts, assignment)

  print(f"\nHasil perolehan nilai {nama_siswa}")
  print(f"Final Score: {final_score:.1f}")
  print(f"Grade: {grade}")

if __name__ == "__main__":
    main()

Masukkan username anda : Kezia
Masukkan password anda : admin1234
Incorrect Password

Masukkan password anda : Bn123
Login Berhasil, Selamat Datang Kezia

Masukkan nama siswa : Kezia
Masukkan Nilai UAS : 91
Masukkan Nilai UTS : 90
Masukkan Nilai Assignment : 95

Hasil perolehan nilai Kezia
Final Score: 91.5
Grade: A
